---

- name: Restart node_red
  service:
    name: "{{ node_red_service }}"
    state: restarted
  notify:
    - Wait for node-red to start in handler

- name: Wait for node-red to start in handler
  wait_for:
    host: "{{ node_red_bind_address.split(':')[0] }}"
    port: "{{ node_red_bind_address.split(':')[1] }}"
